#!/bin/ksh


finddata="$1"

skip=0

while read -r line
do

  if (( skip != 0 ))
  then
	  skip=$(( skip - 1 ))
	  continue;
  fi

  if [ "$line" == "$1" ]
  then
	  skip=3
	  continue
  fi

  printf "%s\n" "$line"

done


