#!/bin/ksh

tempfile=$( mktemp )
tempfile2=$( mktemp )

cat > "$tempfile2"

cat "$tempfile2" | wh_httpext -c  '<input' '/>' -l > "$tempfile"
cat "$tempfile2" | wh_httpext -c  '<button' '</button>' -l >> "$tempfile"

start=1

while read -r line
do

  if (( start == 1 ))
  then
    start=0
  else
    printf "&\n"
  fi

  value_ans=$( echo "$line" | wh_httpext -c 'value="' '"' | tr -d "\n" )
  
  echo "$line" | wh_httpext -c 'name="' '"' -l | tr -d "\n"
  if test -z "$value_ans"
  then
    printf "\n=\n\n"
    continue
  fi
  printf "\n=\n%s\n" "$value_ans"

done < "$tempfile"

rm -f "$tempfile" "$tempfile2"
