#!/bin/ksh

#
#
# Copyright (c) 2022-2023 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#


if ! utilchk 'basicscan_fork' 'sndlog_data' 'optchk'
then

  printf "Missing utility\n" >&2
  exit 1

fi


badarg() {

  printf "To use this program you need to pass four arguments.\n\n" >&2
  printf "Data option \n" >&2
  printf "-s option will redirect data to stdin of fork command\n" >&2
  printf "-a option will redirect data as last argument of fork command\n" >&2
  printf "-A rn special script in basicscan_fork\n" >&2
  printf "-h shows this text\n" >&2
  printf "-o instead of running basicscan_fork\n" >&2
  printf "pass data unix sockets to your own script \n" >&2
  printf "It will be run like this:\n" >&2
  printf "your_script socket_loaddata socket_savedata forknumber\n" >&2
  printf "You can't have both options -s and -a, also -o must be alone\n\n" >&2
  printf "Script that will generate data\n\n" >&2
  printf "Script that will be forked and use passed data\n\n" >&2
  printf "Number of forks.\n\n" >&2
  printf "Script to run one time on each fork creation\n" >&2
  printf "It is a special argument you pass only when option A is passed\n" >&2
  printf "It's returned data is passed to each scripts that use data\n" >&2
  printf "Only forknumber is passed to one time run script\n" >&2
  exit

}

if test -z "$1"
then
  badarg
fi
opt="$1"

if test -z "$2"
then
  badarg
fi
loadscript="$2"

if test -z "$3"
then
  badarg
fi
forkscript="$3"

if test -z "$4"
then
  badarg
fi
forknum="$4"
specscript=''

optstr="$( optchk "$opt" 'asoAh' )" || badarg

opt=0
USEOWN=0

[[ $optstr == *'h'* ]] && badarg
if [[ $optstr == *'o'* ]]
then

  [[ $optstr != 'o' ]] && badarg
  USEOWN=1

else

  [[ $optstr == *'a'* ]]  && [[ $optstr == *'s'* ]] && badarg
  [[ $optstr == *'a'* ]] && opt='a'
  [[ $optstr == *'s'* ]] && opt='s'
  if [[ $optstr == *'A'* ]] 
  then 

   if test -z "$5"
   then
     badarg
   fi
   specscript="$5"
   opt="$opt"'A'

  fi

fi



# !!! TODO check if forknum is number
# TODO make it number use as port and name as sun

#unix socket names we will use
sun_load="$( mktemp )"
sun_ans="$( mktemp )"

# ASK can we protect this why with unix file from race condition ?
# since temp file should never be removed to be safe
rm -r "$sun_load" "$sun_ans" # TODO - this is risky 

# on error send signal. on end send signal too
eval "$loadscript" | sndlog_data -su "$sun_load" &
#basicscan_load "$loadscript" "$sun_load" &

# errocheck this somehow
sndlog_data -lu "$sun_ans" &
loadpid="$!"

# Start forked programs
started_forks=1
while (( "$started_forks" <= "$forknum" ))
do

	started_forks="$(( started_forks + 1 ))"
        if (( USEOWN  ))
        then
          eval "$forkscript"' '"$sun_load"' '"$sun_ans"' '"$started_forks" &
        else
	    basicscan_fork "$opt" "$forkscript" "$sun_load" "$sun_ans" \
              "$started_forks" "$specscript" &
        fi
	sleep 1 # slow start
	#TODO check if there are no errors on starting forks

done

# we break on #1 because this is out last log job
while true
do

	sleep 5
	countjobs="$( jobs -p | wc -l )"
	if (( countjobs == 1 ))
	then
		break
	fi

done

kill -s SIGINT "$loadpid"

rm -rf "$sun_load"
rm -rf "$sun_ans"
