#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#


if test -z "$1"
then
	printf "Need argument to erase from input form\n" 1>&2 
	exit
fi

first=1
found=0
ampersand=0;

while read -r line
do

  if (( "$found" == 0 ))
  then
 	if [ "$line" == "$1" ]
	then
		read -r line
	  	read -r line
	  	found=1;
	  	continue
  	fi
  fi

  if [[ "$line" == '&' ]]
  then
	  ampersand=1
	  continue;
  fi

  if (( ampersand == 1 ))
  then
	  if (( "$first" == 0 ))
	  then
		ampersand=0
	  	printf "&\n"
	  else
		ampersand=0
	  fi
  fi

  first=0
  printf "%s\n" "$line"

done


