#! /bin/ksh

#
#
# Copyright (c) 2022-2023 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if ! utilchk ssconvert
then

  printf "Missing utility\n" >&2
  exit 1

fi

csvfile_existed=0
tempfile="$( mktemp )"

find . -maxdepth 1 -type f\
  \( -iname '*.xlw' -o -iname '*.xls' -o -iname '*.xlsx' \)\
  > "$tempfile"

while IFS= read -r file
do

  newname="${file%.*}"'.csv'
  
  if test -e "$newname"
  then

    printf "File %s already exists\n" "$newname" >&2
    csvfile_existed=1
    continue

  fi

  ! ssconvert "$file" "$newname" && exit 3
  pritnf "%s -> %s\n" "$file" "$newname"

done < "$tempfile"

rm -f "$tempfile"

if (( csvfile_existed ))
then

  printf "Some csv files already existed,\n" >&2
  printf  "program did not overwrite them\n" >&2
  exit 4

fi
