#! /bin/ksh

#
#
# Copyright (c) 2023 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if ! utilchk ssconvert
then

  printf "Missing utility\n" >&2
  exit 1

fi

if (( $# != 1 ))
then

  printf "This program expects one argument\n" >&2
  printf "Excel file to convert\n" >&2
  exit 1

fi

if ! test -e "$1"

  printf "Specified file does not exist\n" >&2
  exit 2

then

if ! test -f "$1"

  printf "Specified file is not regular file\n" >&2
  exit 2

then

newname="${1%.*}"'.csv'
  
if test -e "$newname"
then

  printf "File %s already exists\n" "$newname" >&2
  exit 4 

fi

! ssconvert "$file" "$newname" && exit 3
pritnf "%s -> %s\n" "$file" "$newname"

