#!/bin/ksh

#
#
# Copyright (c) 2023 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if ! utilchk 'ffmpeg'
then

  printf "Missing utilities.\n" >&2
  exit 1

fi

tf="$( mktemp )"
tf2="$( mktemp )"

ffmpeg -nostdin -formats 2>/dev/null > "$tf"

# get those that can be  decoded and encoded
while IFS= read -r line
do

  ans="$( printf "$line" | awk '{ print $1 }' )"
  if [[ "$ans" != 'DE' ]]
  then

    continue

  fi

  
  printf "*." >> "$tf2"
  printf "%s\n" "$line" | awk '{ print $2 }' >> "$tf2"


done < "$tf"

# now find those how are separated D and E
#while IFS= read -r line
#do

#  ans="$( printf "$line" | awk '{ print $1 }' )"
#  if [[ "$ans" != 'D' ]]
#  then

#    continue

#  fi

#  printf '*.'
#echo "$line" | awk '{ print $2 }'


#done < "$tf"

cat "$tf2"

rm -f "$tf" "$tf2"

