#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#



tempfile=$( mktemp )
tempdata=$( mktemp )'.mp3'

find . -type f -iname '*.MP3' > "$tempfile"


while IFS= read -r line
do
  
  printf "%s\n" "$line"
  testvar=''
  testvar=$( ffprobe -loglevel 'warning' "$line" 2>&1 )
  if test -n "$testvar"
  then

    printf "\n\n%s\n" "$line"
    rm -f "$tempdata"
    ffmpeg -nostdin -loglevel 'warning' -i "$line" -acodec copy "$tempdata"
    printf "\n"
    rm -f "$line"
    cp "$tempdata" "$line"
    printf "\nAttempted to fix %s\n\n" "$line"

  fi

done < "$tempfile"

rm -f "$tempgile" "$tempdata"

