#! /bin/ksh

#
#
# Copyright (c) 2022 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if test -z "$1"
then
	printf "%s\n" "No file name specified" >&2
	exit
fi

if ! test -e "$1"
then
	printf "%s\n" "File does not exist" >&2
	exit
fi

newname=$( printf "%s" "$1" | rmvmb )
echo "$newname"
echo "$1"

if [ "$newname" == "$1" ]
then
	exit
fi

if test -e "$newname"
then
	printf "%s\n" "File using fixedname exists, nothing is being done to prevent data getting overwritten" >&2
	exit
fi

if ! mv "$1" "$newname"
then
	echo "$?"
	printf "%s%s\n" "Could not move file " >&2
fi


