#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#



tempfile=$( mktemp )
tempfile2=$( mktemp )

cat > "$tempfile2"

cat "$tempfile2" | strext -c  '<input' '/>' -l > "$tempfile"
cat "$tempfile2" | strext -c  '<textarea' '>' -l >> "$tempfile"
cat "$tempfile2" | strext -c  '<button' '</button>' -l >> "$tempfile"

start=1

while read -r line
do

  name=$( echo "$line" | strext -c 'name="' '"' -l | tr -d "\n" )
  if test -z "$name"
  then
    name=$( echo "$line" | strext -c 'name='\' \' -l | tr -d "\n" )
    if test -z "$name"
    then
      continue
    fi
  fi

  value_ans=$( echo "$line" | strext -c 'value="' '"' | tr -d "\n" )
  if test -z "$value_ans"
  then
    value_ans=$( echo "$line" | strext -c 'value='\' \' | tr -d "\n" )
  fi

  if (( start == 1 ))
  then
    start=0
  else
    printf "&\n"
  fi

  printf "%s" "$name"

  if test -z "$value_ans"
  then
    printf "\n=\n\n"
    continue
  fi
  printf "\n=\n%s\n" "$value_ans"

done < "$tempfile"

rm -f "$tempfile" "$tempfile2"
