#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#




tempfile="$( mktemp )"
tempfile2="$( mktemp )"
tempfile3="$( mktemp )"

cat | httphb_split -h | lext -c 'Set-Cookie: ' ';' -l  > "$tempfile"

oldcookie="$1"
echo "$oldcookie" | lext -c 'Cookie:' '' | tr " " "\n" | tr -d ";" | awk NF > "$tempfile2"

while IFS= read -r cookie
do

  exist=0

  oldc="$( echo "$cookie" | lext -c '' '='  )"
  while read -r line
  do

    newc="$( echo "$line" | lext -c '' '=' )"
    if [ "$oldc" == "$newc" ]
    then

      exist=1
      break;

    fi

  done < "$tempfile"

  if (( exist == 0 )) 
  then
    printf "%s\n" "$cookie" >> "$tempfile3"
  fi

done < "$tempfile2"

while read -r line
do

  printf "%s\n" "$line" >> "$tempfile3"

done < "$tempfile"


printf "Cookie:"
first=1;
while read -r line
do
  
  if (( first == 1 ))
  then
    printf " %s" "$line"
    first=0
    continue
  fi

  printf "; %s" "$line"

done < "$tempfile3"

rm -f "$tempfile" "$tempfile2" "$tempfile3"
