#!/bin/ksh

if [[ "$#" < 1 ]]
then
  printf "%s\n" "Provide url minimum."
  printf "%s\n" "Syntax: getpage url user-agent cookie IP port disableHTTPS"
  printf "%s\n" "disableHTTPS - leave it empty for https"
  printf "%s\n" "Any argument passed will disable https"
  exit
fi

url="$1"
cookie="$3"

if test -z "$2"
then
  ua="gethttp10 bot, ""$( uname -srm )"
else
  ua="$2"
fi

if test -z "$7"
then
  https=1
else
  https=0
fi

setreq() {

host="${url#*//}"
host="${host%%/*}"

if (( $1 == 1 ))
then
  httpscmd[0]='-c'
  httpscmd[1]='-e'
  httpscmd[2]="$host"
fi

path="${url#*//}"
if [[ "$path" == */* ]]
then
  path="${path#*/}"
  path='/'"$path"
else
  path='/'
fi

}

setreq "$https"

if test -z "$4"
then
  IP=$( tor-resolve "$host" )
else
  IP="$4"
fi

if test -z "$6"
then
  TORport=9050
else
  TORport="$6"
fi

if (( https ))
then
  if test -z "$5"
  then
    port=443
  else
    port="$5"
  fi
else
  if test -z "$5"
  then
    port=80
  else
    port="$5"
  fi
fi

req() {

printf "GET %s HTTP/1.0\n" "$path"
printf "Host: %s\n" "$host"
printf "User-Agent: %s\n" "$ua"
printf "%s\n" "$cookie"
printf  "%s\n" 'Accept: text/html,application/xhtml+xml'\
',application/xml;q=0.9,image/webp,*/*;q=0.8'
printf "%s\n" 'Accept-Language: en-US,en;q=0.5'

}

tempfile=$( mktemp )
tempfile2=$( mktemp )

while true
do
 
  req | httpreq_addcrlf |
  nc -w '10' "${httpscmd[@]}" "$IP" "$port" > "$tempfile"
  cat "$tempfile" | httphb_split -h > "$tempfile2"
  status_code=$( head -n 1 "$tempfile2" )
  if [[ "$status_code" == *301* ]]
  then

	  url=$( cat "$tempfile2" | strext -c 'Location: ' '' | tr -d '\r\n' )
	  if (( https == 0 ))
	  then
		 if [[ 'https' == "${url%%://*}" ]] 
		 then 
			 https=1
			 if test -z "$5"
			 then
				 port=443
			 fi
		 fi
	  fi


          setreq "$https"
          if test -z "$4"
          then
            IP=$( tor-resolve "$host" )
          else
            IP="$4"
          fi
	  continue

  fi
  break

done

cat "$tempfile"

rm -f "$tempfile" "$tempfile2"
