#!/bin/ksh

if [[ "$#" < 2 ]]
then
  printf "Provide url and user-agent minimum.\n"
  printf "Syntax: getpage url user-agent cookie IP\n"
  exit
fi

url="$1"
ua="$2"
cookie="$3"

setreq() {

host="${url#*//}"
host="${host%%/*}"

path="${url#*//}"
if [[ "$path" == */* ]]
then
  path="${path#*/}"
  path='/'"$path"
else
  path='/'
fi

}

setreq

if test -z "$4"
then
  IP=$( tor-resolve "$host" )
else
  IP="$4"
fi


req() {

printf "GET %s HTTP/1.0\n" "$path"
printf "Host: %s\n" "$host"
printf "User-Agent: %s\n" "$ua"
printf "%s\n" "$cookie"
printf  "%s\n" 'Accept: text/html,application/xhtml+xml'\
',application/xml;q=0.9,image/webp,*/*;q=0.8'
printf "%s\n" 'Accept-Language: en-US,en;q=0.5'

}

tempfile=$( mktemp )
tempfile2=$( mktemp )

while
do
 
  req | httpreq_addcrlf | nc -w 10 -c -e "$host" -X '5' -x 'localhost:9050' "$IP" '443' > "$tempfile"
  cat "$tempfile" | httphb_split -h > "$tempfile2"
  status_code=$( head -n 1 "$tempfile2" )
  if [[ "$status_code" == *301* ]]
  then

	  url=$( cat "$tempfile2" | strext -c 'Location: ' '' | tr -d '\r\n' )
          setreq
          if test -z "$4"
          then
            IP=$( tor-resolve "$host" )
          else
            IP="$4"
          fi
	  continue

  fi
  break

done

cat "$tempfile"

rm -f "$tempfile" "$tempfile2"
