#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#


tf="$( mktemp )"
find . -type f \( -iname '*.mp3' -o -iname '*.flac' \) -print > "$tf"

while IFS= read -r line
do

  ans="$( ffprobe -show_format "$line" 2>/dev/null | grep -F 'nb_streams' )"
  ans="${ans##*=}"
  if (( ans != 1 ))
  then

    printf "File: %s\n Number of  streams: %s\n" "$line" "$ans"
    ffprobe -show_streams "$line" 2>/dev/null | grep -E '(index|codec_type)'
    printf "\n"

  fi

done < "$tf"

rm -f "$tf"
