#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#



pkg_add firefox
pkg_add surf
pkg_add tor
pkg_add tor-browsera

pkg_add fvwm2
pkg_add feh
pkg_add compton
pkg_add xdotool

pkg_add cups

pkg_add mupdf
pkg_add p5-Image-ExifTool
pkg_add qpdf

pkg_add gimp
pkg_add tesseract

pkg_add mpd
pkg_add mpc
pkg_add audacity
pkg_add cmus
pkg_add eyeD3
pkg_add calibre

pkg_add vlc
pkg_add ffmpeg
pkg_add x264
pkg_add x265

pkg_add gcc
pkg_add cmake
pkg_add git

pkg_add clutter
pkg_add conky

pkg_add vim
pkg_add rsync

pkg_add irssi

pkg_add ansiweather
