#!/bin/ksh

#
#
# Copyright (c) 2023 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#


if ! utilchk  'sh_getopt'
then

  printf "Missing utility.\n" >&2
  exit 1

fi

set -A ksh_args -- "$@"

# Last passed argument should be options so we save it and remove
options_str="${ksh_args[ ${#ksh_args[@]} - 1 ]}"
unset  "ksh_args[ "${#ksh_args[@]}" - 1 ]"

if ! sh_getopt "${ksh_args[@]}" "$options_str"
then

  # TODO we need to distinguish error
  printf "Failed on sh_getopt command\n" >&2
  printf "Check if options are correct\n" >&2
  exit 2

fi

