#!/bin/ksh

#
#
# Copyright (c) 2022 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

tmpfile="$( mktemp )"
find . -type f -iname '*.jpg' > "$tmpfile"

while IFS= read -r imgfile
do

	du -h "$imgfile"
	mogrify -quality 85 "$imgfile"
	printf "Converted: "
	du -h "$imgfile"

done < "$tmpfile"

find . -type f -iname '*.png' > "$tmpfile"

while IFS= read -r imgfile
do

	du -h "$imgfile"
	newname="${imgfile%.*}"'.jpg'
	if test -e "$newname"
	then
		printf "File allready exist: %s\n" "$newname" >&2
		continue
	fi
	convert "$imgfile" "$newname"
	mogrify -quality 85 "$newname"
	rm "$imgfile"
	du -h "$newname"

done < "$tmpfile"


find . -type f -iname '*.jpeg' > "$tmpfile"

while IFS= read -r imgfile
do

	du -h "$imgfile"
	newname="${imgfile%.*}"'.jpg'
	if test -e "$newname"
	then
		printf "File allready exist: %s\n" "$newname" >&2
		continue
	fi
	convert "$imgfile" "$newname"
	mogrify -quality 85 "$newname"
	rm "$imgfile"
	du -h "$newname"

done < "$tmpfile"



find . -type f -iname '*.webp' > "$tmpfile"

while IFS= read -r imgfile
do

	du -h "$imgfile"
	newname="${imgfile%.*}"'.jpg'
	if test -e "$newname"
	then
		printf "File allready exist: %s\n" "$newname" >&2
		continue
	fi
	convert "$imgfile" "$newname"
	mogrify -quality 85 "$newname"
	rm "$imgfile"
	du -h "$newname"

done < "$tmpfile"







