#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if ! utilchk 'pdfinfo' 'qpdf' 'exiftool'
then

  printf "There are utilities missing to run this script\n" >&2
  exit 1

fi

if (( $# != 1 ))
then

  printf "You must provide one pdf path, only one argument\n" >&2
  exit 1

fi

if ! test -e "$1"
then

  printf "File does not exist\n" >&2
  exit 2

fi

if ! test -f "$1"
then

  printf "File is not regular file\n" >&2
  exit 2

fi


tf="$( mktemp )"
tf2="$( mktemp )"


printf "PDF file: %s\n" "$1"
pdfinfo "$1"

! qpdf "$1" "$tf" && exit 3
! exiftool '-all:all=' "$tf" && exit 3
! qpdf "$tf" "$tf2" && exit 3
! mv "$tf2" "$1" && exit 3

pdfinfo "$1"

rm -f "$tf" "$tf2"
