#!/bin/ksh

#
#
# Copyright (c) 2023 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if ! utilchk 'pdfinfo' 'qpdf' 'exiftool'
then

  printf "There are utilities missing to run this script\n" >&2
  exit 1

fi

if (( "$#" != 0 ))
then

  printf "This program does not take any arguments\n" >&2
  printf "It runs in current directory\n" >&2
  exit 2

fi


tf="$( mktemp )"
tf2="$( mktemp )"
tf3="$( mktemp )"

find . -type f -iname '*.pdf' > "$tf"

while IFS= read -r pdffile
do

  printf "PDF file: %s\n" "$pdffile"
  pdfinfo "$pdffile"

  qpdf "$pdffile" "$tf2"
  exiftool '-all:all=' "$tf2"
  qpdf "$tf2" "$tf3"
  mv "$tf3" "$pdffile"

  pdfinfo "$pdffile"

done < "$tf"

rm -f "$tf" "$tf2" "$tf3"
