#!/bin/ksh

if [[ "$#" != 5 ]]
then
  printf "Syntax: postreq url user-agent cookie IP postbody\n"
  exit
fi

url="$1"
ua="$2"
cookie="$3"

setreq() {

host="${url#*//}"
host="${host%%/*}"

path="${url#*//}"
if [[ "$path" == */* ]]
then
  path="${path#*/}"
  path='/'"$path"
else
  path='/'
fi

}

setreq

if test -z "$4"
then
  IP=$( tor-resolve "$host" )
else
  IP="$4"
fi

postbody="$5"


req() {

printf "POST %s HTTP/1.0\n" "$path"
printf "Host: %s\n" "$host"
printf "User-Agent: %s\n" "$ua"
printf "%s\n" "$cookie"
printf  "%s\n" 'Accept: text/html,application/xhtml+xml'\
',application/xml;q=0.9,image/webp,*/*;q=0.8'
printf "%s\n" 'Accept-Language: en-US,en;q=0.5'
printf "%s\n" 'Content-Type: application/x-www-form-urlencoded'
printf "%s%d\n" 'Content-Length: ' "${#postbody}"

}

tempfile=$( mktemp )
tempfile2=$( mktemp )
 
{ req | httpreq_addcrlf; printf "%s" "$postbody"; } |\
  nc -w 10 -c -e "$host" -X '5' -x 'localhost:9050' "$IP" '443'
