#! /bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#

if test -z "$1"
then

	printf "You need to pass port for tor proxy where we will run it\n" >&2
	exit

fi
torport="$1"

# TODO check if number

tordatadir=$( mktemp -d )
torconf=$( mktemp )

torproxy='localhost:'"$torport"
tor --quiet --SocksPort "$torport" \
  --DataDirectory "$tordatadir" -f "$torconf" &
torpid="$!"

#restart tor on SIGINT
trap 'kill -SIGHUP '"$torpid" SIGINT

#kill on leaving term
trap 'kill -SIGTERM '"$torpid"';exit' SIGHUP


# just wait to leave
while true
do

  sleep 60

done

return 0

