#!/bin/ksh

#
#
# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#



if test -z "$1"
then
	echo "You need to pass domain name, for example domain.org"
	exit
fi

tempfile=$( mktemp )

for word in 'www' 'mail' 'mx' 'ns1' 'ns2' 'm' 'ns' 'mx0' \
'mail2' 'remote' 'mx1' 'mailserver' 'smtp' 'blog' 'webmail' \
'server' 'ns3' 'mx2' 'mail1' 'redbusprimarydns' 'redbussecondarydns' \
'vpn' 'dev' 'mx7' 'secure' 'shop' 'ns4' 'cloud' 'ftp'  'mx01'  'api' \
'portal' 'dns1' 'test' 'dns2' 'email' 'host' 'app' 'support' 'ww1' \
'mailin2' 'mailin1' 'pop' 'bbs' 'web' 'r.1' 'r.2' 'r.3' 'forum' 'owa' 'wiki'
do
	printf "%s " "$word"
	tor-resolve "$word"."$1" | tee -a "$tempfile"

done

printf "\nUNIQ SUMMARY:\n"
sort "$tempfile" | uniq

rm -f "$tempfile"
